
GOOGLE_API_KEY : 'GOOGLE_API_KEY'
ROBOFLOW_API_KEY: 'ROBOFLOW_API_KEY'
app_url: "https://detect.roboflow.com"
model_id: "road-objects-qvjnl/2"

download_location: 'images'
output_location: 'output'
input_shapefile_dir: 'data shapefile/sample.shp'