
GOOGLE_API_KEY : 'GOOGLE_API_KEY'
ROBOFLOW_API_KEY: 'ROBOFLOW_API_KEY'
app_url: "https://detect.roboflow.com"
model_id: "road-objects-qvjnl"
version: '2'

download_location: 'images'
output_location: 'output'
input_shapefile_dir: 'data shapefile/sample.shp'
input_crash_locations_dir: 'crash_data_unique.csv'